-- Minimal baseline required to rebuild the local challenge database from scratch.
-- Later imported migrations assume these core tables and helper functions exist.

CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_week_start(input_date date DEFAULT CURRENT_DATE)
RETURNS date
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT (input_date - ((EXTRACT(DOW FROM input_date)::int + 6) % 7))::date;
$$;

CREATE OR REPLACE FUNCTION public.setup_cron_extensions()
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  CREATE EXTENSION IF NOT EXISTS pg_cron;
  CREATE EXTENSION IF NOT EXISTS pg_net;
$$;

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text,
  avatar_url text,
  preferences jsonb DEFAULT '{}'::jsonb,
  consents jsonb DEFAULT '[]'::jsonb,
  current_month_points integer NOT NULL DEFAULT 0,
  linkedin_token text,
  linkedin_token_expires_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.sources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  apiurl text NOT NULL,
  type text NOT NULL,
  language text DEFAULT 'English',
  industries text[] DEFAULT '{}'::text[],
  locations text[] DEFAULT '{}'::text[],
  article_extraction_hints jsonb NOT NULL DEFAULT '{}'::jsonb,
  processed boolean DEFAULT false,
  need_filter boolean DEFAULT false,
  lastfetched timestamptz,
  last_inspected_at timestamptz,
  extraction_limit integer NOT NULL DEFAULT 5,
  article_url_patterns jsonb,
  article_url_exclude_patterns jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.articles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  url text NOT NULL,
  summary text,
  content text,
  imageurl text NOT NULL DEFAULT '',
  sourceid uuid REFERENCES public.sources(id) ON DELETE SET NULL,
  publicationdate timestamptz,
  retrievedat timestamptz DEFAULT now(),
  industries text[] DEFAULT '{}'::text[],
  locations jsonb DEFAULT '[]'::jsonb,
  normalized_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  article_id uuid NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  content text NOT NULL,
  ai_content text,
  status text NOT NULL DEFAULT 'revision',
  scheduled_for timestamptz,
  linkedin_post_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT posts_status_check CHECK (status = ANY (ARRAY['revision', 'approved', 'scheduled', 'published', 'generating']))
);

CREATE TABLE public.user_goals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  week_start date NOT NULL,
  target_posts integer NOT NULL DEFAULT 4,
  completed_posts integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, week_start)
);

CREATE TABLE public.user_streaks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  current_streak integer NOT NULL DEFAULT 0,
  longest_streak integer NOT NULL DEFAULT 0,
  last_activity_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.profile_monthly_points (
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  period_start date NOT NULL DEFAULT date_trunc('month', CURRENT_DATE)::date,
  points integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (profile_id, period_start)
);

CREATE TABLE public.notification_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text,
  entity_id uuid,
  payload jsonb DEFAULT '{}'::jsonb,
  processed boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.user_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint NOT NULL REFERENCES public.notification_events(id) ON DELETE CASCADE,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending',
  sent_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.editorial_configs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name text,
  editorial_prompt text,
  summary_prompt text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public."specialized-extraction" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id uuid,
  person_name text,
  keywords text,
  region text,
  language text,
  amount integer DEFAULT 0,
  "lastLink" text,
  extracted boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_articles_sourceid ON public.articles(sourceid);
CREATE INDEX idx_articles_publicationdate ON public.articles(publicationdate DESC);
CREATE INDEX idx_posts_user_id ON public.posts(user_id);
CREATE INDEX idx_posts_article_id ON public.posts(article_id);
CREATE INDEX idx_profile_monthly_points_period ON public.profile_monthly_points(period_start DESC);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_streaks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_monthly_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.editorial_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."specialized-extraction" ENABLE ROW LEVEL SECURITY;
